// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eeta/billboard/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateBillboardRequest struct {
	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url         string        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type        BillboardType `protobuf:"varint,4,opt,name=type,proto3,enum=eeta.billboard.BillboardType" json:"type,omitempty"`
	MinPrice    types.Coin    `protobuf:"bytes,5,opt,name=min_price,json=minPrice,proto3" json:"min_price"`
}

func (m *CreateBillboardRequest) Reset()         { *m = CreateBillboardRequest{} }
func (m *CreateBillboardRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBillboardRequest) ProtoMessage()    {}
func (*CreateBillboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d22ad6fda9c78063, []int{0}
}
func (m *CreateBillboardRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateBillboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateBillboardRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateBillboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBillboardRequest.Merge(m, src)
}
func (m *CreateBillboardRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateBillboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBillboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBillboardRequest proto.InternalMessageInfo

func (m *CreateBillboardRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBillboardRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateBillboardRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateBillboardRequest) GetType() BillboardType {
	if m != nil {
		return m.Type
	}
	return BillboardType_ONLINE
}

func (m *CreateBillboardRequest) GetMinPrice() types.Coin {
	if m != nil {
		return m.MinPrice
	}
	return types.Coin{}
}

type CreateBillboardResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *CreateBillboardResponse) Reset()         { *m = CreateBillboardResponse{} }
func (m *CreateBillboardResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBillboardResponse) ProtoMessage()    {}
func (*CreateBillboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d22ad6fda9c78063, []int{1}
}
func (m *CreateBillboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateBillboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateBillboardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateBillboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBillboardResponse.Merge(m, src)
}
func (m *CreateBillboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateBillboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBillboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBillboardResponse proto.InternalMessageInfo

func (m *CreateBillboardResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateBillboardRequest)(nil), "eeta.billboard.CreateBillboardRequest")
	proto.RegisterType((*CreateBillboardResponse)(nil), "eeta.billboard.CreateBillboardResponse")
}

func init() { proto.RegisterFile("eeta/billboard/tx.proto", fileDescriptor_d22ad6fda9c78063) }

var fileDescriptor_d22ad6fda9c78063 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0xb7, 0xb0, 0x1a, 0x29, 0x09, 0x9a, 0xc6, 0xc0, 0x4a, 0x62, 0xdd, 0x70, 0x50, 0xbc,
	0x74, 0x05, 0xaf, 0x9e, 0xe0, 0x6c, 0x62, 0x36, 0x9e, 0xbc, 0x98, 0xfd, 0x33, 0x21, 0x8d, 0x6c,
	0x5b, 0xb7, 0xc5, 0xc0, 0x5b, 0xf8, 0x58, 0x1c, 0xf1, 0xe6, 0xc9, 0x18, 0x78, 0x11, 0xb3, 0x5d,
	0x24, 0x88, 0x26, 0xde, 0xbe, 0xcc, 0xf7, 0x4d, 0xa7, 0xbf, 0x4e, 0x71, 0x0b, 0xc0, 0x44, 0x41,
	0xcc, 0xc7, 0xe3, 0x58, 0x46, 0x79, 0x1a, 0x98, 0x29, 0x53, 0xb9, 0x34, 0x92, 0x34, 0x0a, 0x83,
	0x6d, 0x8c, 0x36, 0xdd, 0x09, 0x6e, 0x54, 0x99, 0x6f, 0xd3, 0x44, 0xea, 0x4c, 0xea, 0x20, 0x8e,
	0x34, 0x04, 0x2f, 0xbd, 0x18, 0x4c, 0xd4, 0x0b, 0x12, 0xc9, 0xc5, 0xda, 0x3f, 0x1e, 0xc9, 0x91,
	0xb4, 0x32, 0x28, 0x54, 0x59, 0xed, 0xbc, 0x21, 0xdc, 0x1c, 0xe6, 0x10, 0x19, 0x18, 0x7c, 0x9f,
	0x17, 0xc2, 0xf3, 0x04, 0xb4, 0x21, 0x04, 0xbb, 0x22, 0xca, 0xc0, 0x43, 0x3e, 0xea, 0xd6, 0x42,
	0xab, 0x89, 0x8f, 0xeb, 0x29, 0xe8, 0x24, 0xe7, 0xca, 0x70, 0x29, 0xbc, 0x8a, 0xb5, 0xb6, 0x4b,
	0xe4, 0x08, 0x57, 0x27, 0xf9, 0xd8, 0xab, 0x5a, 0xa7, 0x90, 0xa4, 0x87, 0x5d, 0x33, 0x53, 0xe0,
	0xb9, 0x3e, 0xea, 0x36, 0xfa, 0xa7, 0xec, 0x27, 0x17, 0xdb, 0xcc, 0xbd, 0x9f, 0x29, 0x08, 0x6d,
	0x94, 0xdc, 0xe0, 0x5a, 0xc6, 0xc5, 0xa3, 0xca, 0x79, 0x02, 0xde, 0x9e, 0x8f, 0xba, 0xf5, 0xfe,
	0x09, 0x2b, 0xf9, 0x58, 0xc1, 0xc7, 0xd6, 0x7c, 0x6c, 0x28, 0xb9, 0x18, 0xb8, 0xf3, 0x8f, 0x33,
	0x27, 0x3c, 0xc8, 0xb8, 0xb8, 0x2b, 0x1a, 0x3a, 0x97, 0xb8, 0xf5, 0x0b, 0x49, 0x2b, 0x29, 0x34,
	0x90, 0x06, 0xae, 0xf0, 0xd4, 0x12, 0xb9, 0x61, 0x85, 0xa7, 0xfd, 0x27, 0x5c, 0xbd, 0xd5, 0x23,
	0x92, 0xe2, 0xc3, 0x9d, 0x0e, 0x72, 0xbe, 0x7b, 0xcf, 0xbf, 0x5f, 0xa9, 0x7d, 0xf1, 0x6f, 0xae,
	0x1c, 0xdd, 0x71, 0x06, 0x57, 0xf3, 0x25, 0x45, 0x8b, 0x25, 0x45, 0x9f, 0x4b, 0x8a, 0x5e, 0x57,
	0xd4, 0x59, 0xac, 0xa8, 0xf3, 0xbe, 0xa2, 0xce, 0x43, 0xd3, 0xee, 0x76, 0xba, 0xfd, 0x0d, 0x66,
	0x0a, 0x74, 0xbc, 0x6f, 0x97, 0x74, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x1c, 0xea, 0x64,
	0x25, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateBillboard(ctx context.Context, in *CreateBillboardRequest, opts ...grpc.CallOption) (*CreateBillboardResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBillboard(ctx context.Context, in *CreateBillboardRequest, opts ...grpc.CallOption) (*CreateBillboardResponse, error) {
	out := new(CreateBillboardResponse)
	err := c.cc.Invoke(ctx, "/eeta.billboard.Msg/CreateBillboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateBillboard(context.Context, *CreateBillboardRequest) (*CreateBillboardResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBillboard(ctx context.Context, req *CreateBillboardRequest) (*CreateBillboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBillboard not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBillboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBillboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eeta.billboard.Msg/CreateBillboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBillboard(ctx, req.(*CreateBillboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eeta.billboard.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBillboard",
			Handler:    _Msg_CreateBillboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eeta/billboard/tx.proto",
}

func (m *CreateBillboardRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateBillboardRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateBillboardRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Type != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateBillboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateBillboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateBillboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateBillboardRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovTx(uint64(m.Type))
	}
	l = m.MinPrice.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *CreateBillboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateBillboardRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateBillboardRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateBillboardRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= BillboardType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateBillboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateBillboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateBillboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
